import ftplib 
session = ftplib.FTP('localhost', 'root', '')
file = open('/home/qawbecrdteyf/Desktop/AndroidStudioProjects/St-matlab/prediction.csv', 'rb')
file2 = open('/home/qawbecrdteyf/Desktop/AndroidStudioProjects/St-matlab/data.json', 'rb')
session.cwd('/chirag/')
#session.storbinary('STOR prediction.csv', file)
session.storbinary('STOR dataf.json', file2)
file.close()
file2.close()
session.quit()
